### ISSUE TITLE
Bug: page layout/zoom scale not kept/wrongly initiated after loading a new PDF

### ISSUE THREAD

**Issue by xiaohanyu** [pdf-viewer-react/react-pdf#3]
Hello,

I am coming from [react-pdf-viewer](https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1858) because it seems dead and not maintained any more.

I am doing a LaTeX based resume builder product called [PPResume](https://ppresume.com), my use case here:

1. the resume builder has a form input pane on the left and a PDF preview pane on the right
2. when user input things in the form, the resume builder would generate a new PDF and show it to users (internally, we pass the generated PDF in base64 encoded blob)

Recently I am trying to migrate to react-pdf (I already bought the license), almost everything looks OK however I do have one serious bug which is the only show stopper for me.

Please take the following demo:

https://github.com/user-attachments/assets/f127bb21-0ae0-49f7-9d89-ad34f721abad

At 00:00:40 and 00:00:60, the pages layout are completed overlapped, at 00:00:90, some zoom options (`page fit`) are not functional as expected.

I thought this may be due to my setup/configuration issue. However I found even the official [next.js demo](https://github.com/pdf-viewer-react/starter-rp-next-ts) has these issues, again, demo:

https://github.com/user-attachments/assets/35bbb96e-c7e3-4c76-8b8a-1dbccb791825

At 00:00:20, when use the PDF viewer to open a new file for the second time, the pages layout is broken, margins between pages is way too large and some page zoom functions stops working again.

I tried to pass `initialScale={ZoomLevel.PAGE_FIT}` to `RPProvider` to stablize the zoom scale in next.js demo, however this seems not working.

Regards.

**Comment by david-reactpdf** [comment]
Hey @xiaohanyu ,

Thanks so much for the detailed report and the screen recordings—super helpful in understanding the issue clearly.

We’re currently looking into what’s causing the layout and zoom inconsistencies when loading a new PDF. I’ll keep you posted once we’ve got a fix ready.

**Comment by david-reactpdf** [comment]
Hey @xiaohanyu, like #4,  just want to let you know we've published a [new version](https://www.npmjs.com/package/@pdf-viewer/react/v/1.3.0) to address this issue. Hopefully, the experience of loading a new PDF is smoother for you now than that of before.

**Comment by xiaohanyu** [comment]
Hello @david-reactpdf , I've tried with 1.3 however I cannot verify in my local.

There seems to be some new issues:

1. it reports me that my license key is not valid
2. the pdf viewer just load infinitely, reason unknown, I've tried both localhost pdf and remote PDF (from the official demo: https://cdn.codewithmosh.com/image/upload/v1721763853/guides/web-roadmap.pdf), however none of them load as expected.

Checkout demo:

https://github.com/user-attachments/assets/44c093d4-3814-40c8-af5a-cbc6e6c31c23

**Comment by xiaohanyu** [comment]
Further demo:

1. my networking is good, can access google and the remote PDF
2. version 1.0, 1,1, 1,2 and 1.3 all reports the invalid license key issues, is there any remote license verification server under the hood and that license server is down?

This is really weird.

https://github.com/user-attachments/assets/2beda388-75c2-4b08-a817-bac203b5d129

**Comment by david-reactpdf** [comment]
Hi @xiaohanyu ,

Thanks for reporting this and for including all the context.

Just to clarify, React PDF doesn’t use any remote license verification server. The license verification is performed entirely on the frontend, so there’s no dependency on an external service.

After checking, it looks like a license key hasn’t been generated for your local environment (e.g., `localhost:3000`). Each license key is tied to a specific domain. If you’re testing locally, you’ll need to create a separate license key for that domain (in your case, `localhost:3000`) to remove the watermark.

You can refer to the licensing guide here for more details: [https://docs.react-pdf.dev/introduction/licensing](https://docs.react-pdf.dev/introduction/licensing)

**Comment by xiaohanyu** [comment]
Hello @david-reactpdf ,

Thanks for this quick reply.

I've created two additional license, one is for `localhost` and another is for `localhost:3000`, the latter works and the watermark has been removed.

However, it still cannot load the PDF as expected. Reason unknown.

I am available for a live call if you need.

**Comment by david-reactpdf** [comment]
@xiaohanyu 

Thanks for the update, and glad to hear the watermark issue was resolved! Just a quick note: since you created a Specific type license key, you’ll need to include both the domain and port. So a key for `localhost` won’t work for `localhost:3000` (and vice versa).

As for the PDF not loading—are you using our next.js starter project? Would you mind sharing a snippet of your implementation or the project or file where React PDF is being used?

Feel free to drop me an email at david@react-pdf.dev and I’ll be happy to take a closer look.

**Comment by xiaohanyu** [comment]
Hello @david-reactpdf ,

Yes I use https://github.com/pdf-viewer-react/starter-rp-next-ts project.

The good news is, after I fully nuked my `node_modules` under `starter-rp-next-ts` project, it works.

Confirmed that:

- page layout/zoom works when changing PDF, no chaos any more.
- text selection in #4 also works much better than previous version.

Excellent job! I think I can fully migrate my project to this soon.
